[features]
seeds = false
[programs.localnet]
mycalcilatordapp = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "C:\\Users\\ASUS\\.config/solana/FRAuDpAfYkCe7WnKHZ2eCXnocM45rDuRrQHBRVL78RPg.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
